<?php

namespace ContainerP1BCiaX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RLJD5tService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rLJD_5t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rLJD_5t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'livre' => ['privates', '.errored.D0oXl2s', NULL, 'Cannot determine controller argument for "App\\Controller\\AdminController::deleteUser()": the $livre argument is type-hinted with the non-existent class or interface: "App\\Controller\\Livre". Did you forget to add a use statement?'],
        ], [
            'livre' => '?',
        ]);
    }
}
