<?php

namespace ContainerP1BCiaX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YYuHDV4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YYuHDV4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YYuHDV4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'auteurRepository' => ['privates', 'App\\Repository\\AuteurRepository', 'getAuteurRepositoryService', true],
            'genreRepository' => ['privates', 'App\\Repository\\GenreRepository', 'getGenreRepositoryService', true],
            'livreRepository' => ['privates', 'App\\Repository\\LivreRepository', 'getLivreRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'auteurRepository' => 'App\\Repository\\AuteurRepository',
            'genreRepository' => 'App\\Repository\\GenreRepository',
            'livreRepository' => 'App\\Repository\\LivreRepository',
            'paginator' => '?',
        ]);
    }
}
