<?php

namespace ContainerLoYL3Qj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JcRiTrkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jcRiTrk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jcRiTrk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'genreRepository' => ['privates', 'App\\Repository\\GenreRepository', 'getGenreRepositoryService', true],
            'livreRepository' => ['privates', 'App\\Repository\\LivreRepository', 'getLivreRepositoryService', true],
        ], [
            'genreRepository' => 'App\\Repository\\GenreRepository',
            'livreRepository' => 'App\\Repository\\LivreRepository',
        ]);
    }
}
