<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP1BCiaX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP1BCiaX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP1BCiaX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP1BCiaX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP1BCiaX\App_KernelDevDebugContainer([
    'container.build_hash' => 'P1BCiaX',
    'container.build_id' => '665ae4eb',
    'container.build_time' => 1641919537,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP1BCiaX');
